application:
  name: ares
server:
  base-url: https://api.cogoport.com
  port: 8086
  context-path: /payments
router:
  static-resources:
    swagger:
      paths: classpath:META-INF/swagger
      mapping: /swagger/**
executors:
  rabbit:
    type: FIXED
  consumer:
    type: FIXED
netty:
  default:
    allocator:
      max-order: 3

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

services:
  namespace: ${DNS_NAMESPACE:cogoport.prod}

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?preparedStatementCacheQueries=0
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      dialect: POSTGRES
    dms:
      url: r2dbc:postgresql://${UNIFIEDDB_HOST}:${UNIFIEDDB_PORT:6432}/${UNIFIEDDB_NAME}?preparedStatementCacheQueries=0
      username: ${UNIFIEDDB_USER}
      password: ${UNIFIEDDB_PASSWORD}
      dialect: POSTGRES

opensearch:
  host: ${OPENSEARCH_HOST}
  user: ${OPENSEARCH_USER}
  pass: ${OPENSEARCH_PASS}

sentry:
  enabled: ${SENTRY_ENABLED:true}
  dsn: ${SENTRY_DSN:`https://10e833c953b04f429df6a6c8cae72c13@o435527.ingest.sentry.io/6475007`}

cogoport:
  api_url: https://api.cogoport.com
  bearer_token: 0b1848788c34b1099d33baa18f5e413744373abfdc193c69016bfe0e107f7532fc68487c243d90086a6034faea960efa4134395f5b06d1d77329a4b7c2759d15
  bearer_token_new: ${BEARER_TOKEN}
  auth_scope_id: ${AUTHORIZATION_SCOPE_ID}
  internal_url: ${INTERNAL_URL}
  exchange_api:
    url: ${EXCHANGE_CLIENT_LAMBDA_URL}
    version: v1
    auth_token: ${EXCHANGE_API_AUTH_TOKEN}

port_mapping:
  common: ${COMMON_PORT:8089}
  
sage:
  soapUrl: ${SAGE_SOAP_URL}
  user: ${SAGE_SOAP_USER}
  password: ${SAGE_PASSWORD}
  queryClientUrl: ${SAGE_QUERY_CLIENT_URL}
  queryClientPassword: ${SAGE_QUERY_CLIENT_PASSWORD}
  databaseName: ${SAGE_DATABASE_NAME}
  restAPIUser: ${SAGE_REST_API_USER}
  restAPIPassword: ${SAGE_REST_API_PASSWORD}

aws:
  s3:
    bucket: business-finance-prod

tracing:
  exclusions:
    - /payments/prometheus
  jaeger:
    enabled: true
    sampler:
      probability: 1
    sender:
      agentHost: ${GRAFANA_TEMPO_DOMAIN:localhost}
      agentPort: ${GRAFANA_TEMPO_PORT:6831}

rabbitmq:
  uri: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_IP}:${RABBITMQ_PORT}
  consumer-executor: rabbit


lsp:
  coming_soon_banner:
    enabled: true

scheduler:
  enabled: true