environment: ${MICRONAUT_ENVIRONMENTS:local}
micronaut:
  application:
    name: ares
  server:
    port: 8086
    context-path: /payments
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  http:
    client:
      read-timeout: 30s
  executors:
    rabbit:
      type: FIXED
    consumer:
      type: FIXED

server:
  base-url: http://127.0.0.1:8086

netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${DB_HOST:rds-cluster.stage.cogoport.io}:${DB_PORT:6432}/${DB_NAME:ares}?preparedStatementCacheQueries=0
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:A942B37CCFAF5A813B1432CAA209A43B9D144E47AD0DE1549C289C253E556CD5}
      dialect: POSTGRES
    dms:
      url: r2dbc:postgresql://${UNIFIEDDB_HOST:`52.66.190.93`}:${UNIFIEDDB_PORT:6432}/${UNIFIEDDB_NAME:dms}?preparedStatementCacheQueries=0
      username: ${UNIFIEDDB_USER:readuser_unifieddb}
      password: ${UNIFIEDDB_PASSWORD:72fe0630c542cc9ac415bf12a6002149}
      dialect: POSTGRES

services:
  service:
    - id: bf-rails
      url: https://api-mustangs2.dev.cogoport.io
      enabledLocally: true
    - auth: bf-rails
      url: https://api-mustangs2.dev.cogoport.io
      enabledLocally: true
    - id: plutus
      url: https://api.stage.cogoport.io
      enabledLocally: true
    - id: cogo-care
      url: https://tickets.stage.cogoport.io
      enabledLocally: false
  staging: https://api.stage.cogoport.io
  namespace: ${DNS_NAMESPACE:cogoport.stage}
  auth:
    alternateRoute: ${AUTH_ALTERNATE_ROUTE:true}
    authDisabled: ${AUTH_DISABLED:true}
    microserviceAuthToken: ${MS_AUTH_TOKEN:c3ad6b5c-a100-46e3-8728-8e2bf83f7de0}

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

opensearch:
  host: ${OPENSEARCH_HOST:search.stage.cogoport.io}
  user: ${OPENSEARCH_USER:awsadmin}
  pass: ${OPENSEARCH_PASS:Password@123}

sentry:
  enabled: ${SENTRY_ENABLED:false}
  dsn: ${SENTRY_DSN:`https://10e833c953b04f429df6a6c8cae72c13@o435527.ingest.sentry.io/6475007`}

cogoport:
  api_url: ${COGOPORT_API_URL:https://api-mustangs2.dev.cogoport.io}
  bearer_token: '7cff5415-6007-4bab-9f3e-e4a08c11e915'
  bearer_token_new: 90fe8fd9-8760-4e1c-9f74-76c644f52c65
  auth_scope_id: e6efcc61-7e30-4d86-a901-e5d330113205
  internal_url: ${INTERNAL_URL:`https://api-mustangs2.dev.cogoport.io`}
  org_base_url: ${ORG_BASE_URL:`https://app-staging.dev.cogoport.io`}
  partner_base_url: ${partner_base_url:`https://admin-spark5.dev.cogoport.io`}
  exchange_api:
    url: ${EXCHANGE_CLIENT_LAMBDA_URL:`https://api.cogoport.com/athena`}
    version: v1
    auth_token: ${EXCHANGE_API_AUTH_TOKEN:`a4f2243a-402e-4f24-825a-2747f66421c7`}

port_mapping:
  common: ${COMMON_PORT:8089}


sage:
  soapUrl: http://13.126.196.22:8124/soap-generic/syracuse/collaboration/syracuse/CAdxWebServiceXmlCC
  user: admin
  password: admin@2
  queryClientUrl: https://47tol5ixceub6n2jv7smwnxerm0qgmoq.lambda-url.ap-south-1.on.aws
  queryClientPassword: 80D705BDB766333C658206B381C969FE
  databaseName: 'COGO4'
  loginUrl: ${ SAGE_LOGIN_URL:`http://13.126.196.22/` }
  username: ${ SAGE_REST_API_USER:`rajveer.singh@cogoport.com` }
  userpassword: ${ SAGE_REST_API_PASSWORD:`Abcd@12345` }

ares:
  settlement:
    crossTradeParty: ${CROSS_TRADE_PARTY_SETTLEMENT:false}

aws:
  s3:
    bucket: business-finance-test

rabbitmq:
  uri: amqp://${RABBITMQ_USER:guest}:${RABBITMQ_PASS:guest}@${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}
  consumer-executor: rabbit

lsp:
  coming_soon_banner:
    enabled: false

scheduler:
  enabled: false