application:
  name: ares
server:
  port: 8086
  context-path: /payment
router:
  static-resources:
    swagger:
      paths: classpath:META-INF/swagger
      mapping: /swagger/**
netty:
  default:
    allocator:
      max-order: 3

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      dialect: POSTGRES

opensearch:
  host: ${OPENSEARCH_HOST}
  user: ${OPENSEARCH_USER}
  pass: ${OPENSEARCH_PASS}
