application:
  name: ares
server:
  port: 8086
  context-path: /payments
router:
  static-resources:
    swagger:
      paths: classpath:META-INF/swagger
      mapping: /swagger/**
metrics:
  enabled: true
  export:
    prometheus:
      enabled: true
      descriptions: true
      step: PT1M
  binders:
    r2dbc:
      enabled: false
netty:
  default:
    allocator:
      max-order: 3

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

r2dbc:
  datasources:
    default:
      datasources:
        default:
          url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?preparedStatementCacheQueries=0
          username: ${DB_USER}
          password: ${DB_PASSWORD}

kafka:
  bootstrap:
    servers: ${KAFKA_SERVERS}
  security:
    protocol: SASL_SSL
  sasl:
    mechanism: AWS_MSK_IAM
    jaas:
      config: software.amazon.msk.auth.iam.IAMLoginModule required;
    client:
      callback:
        handler:
          class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

opensearch:
  host: ${OPENSEARCH_HOST}
  user: ${OPENSEARCH_USER}
  pass: ${OPENSEARCH_PASS}

cogoport:
  api_url: https://api-mustangs4.dev.cogoport.io
  bearer_token: '7cff5415-6007-4bab-9f3e-e4a08c11e915'
  bearer_token_new: 0c320283-6f34-42d0-ac1d-e3390049fe65
  auth_scope_id: 0c320283-6f34-42d0-ac1d-e3390049fe65

endpoints:
  prometheus:
    sensitive: false

otel:
  exporter:
    otlp:
      traces:
        endpoint: http://${GRAFANA_AGENT_DOMAIN:localhost}:${GRAFANA_AGENT_PORT:4317}
  service:
    name: ares
  traces:
    exporter: otlp
  exclusions:
    - /payments/prometheus
