application:
  name: ares
server:
  base-url: https://api.stage.cogoport.io
  port: 8086
  context-path: /payments
router:
  static-resources:
    swagger:
      paths: classpath:META-INF/swagger
      mapping: /swagger/**
executors:
  rabbit:
    type: FIXED
  consumer:
    type: FIXED
netty:
  default:
    allocator:
      max-order: 3

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

r2dbc:
  datasources:
    default:
      datasources:
        default:
          url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?preparedStatementCacheQueries=0
          username: ${DB_USER}
          password: ${DB_PASSWORD}
    dms:
      url: r2dbc:postgresql://${UNIFIEDDB_HOST}:${UNIFIEDDB_PORT:6432}/${UNIFIEDDB_NAME}?preparedStatementCacheQueries=0
      username: ${UNIFIEDDB_USER}
      password: ${UNIFIEDDB_PASSWORD}
      dialect: POSTGRES

services:
  namespace: ${DNS_NAMESPACE:cogoport.stage}
  auth:
    alternateRoute: ${AUTH_ALTERNATE_ROUTE:false}
    authDisabled: ${AUTH_DISABLED:true}
    microserviceAuthToken: ${MS_AUTH_TOKEN:c3ad6b5c-a100-46e3-8728-8e2bf83f7de0}

opensearch:
  host: ${OPENSEARCH_HOST}
  user: ${OPENSEARCH_USER}
  pass: ${OPENSEARCH_PASS}

cogoport:
  api_url: ${COGOPORT_API_URL:https://api-mustangs4.dev.cogoport.io}
  bearer_token: '7cff5415-6007-4bab-9f3e-e4a08c11e915'
  bearer_token_new: 0c320283-6f34-42d0-ac1d-e3390049fe65
  auth_scope_id: 0c320283-6f34-42d0-ac1d-e3390049fe65
  internal_url: ${INTERNAL_URL:`https://api-mustangs5.dev.cogoport.io`}
  exchange_api:
    url: ${EXCHANGE_CLIENT_LAMBDA_URL:`https://api.cogoport.com/athena`}
    version: v1
    auth_token: ${EXCHANGE_API_AUTH_TOKEN:`a4f2243a-402e-4f24-825a-2747f66421c7`}

port_mapping:
  common: ${COMMON_PORT:8089}

sage:
  soapUrl: http://13.126.196.22:8124/soap-generic/syracuse/collaboration/syracuse/CAdxWebServiceXmlCC
  user: admin
  password: admin@2
  queryClientUrl: https://gozaf35uzpkokesxfgw3g2ribi0hddzk.lambda-url.ap-south-1.on.aws
  queryClientPassword: KjjzzU2qneGMtzQQyFJ9QwEiPMFYZgut
  databaseName: 'COGO2'
  loginUrl: ${ SAGE_LOGIN_URL:`http://13.126.196.22/` }
  username: ${ SAGE_REST_API_USER:`rajveer.singh@cogoport.com` }
  userpassword: ${ SAGE_REST_API_PASSWORD:`Abcd@12345` }

tracing:
  exclusions:
    - /payments/prometheus
  jaeger:
    enabled: true
    sampler:
      probability: 1
    sender:
      agentHost: ${GRAFANA_TEMPO_DOMAIN:localhost}
      agentPort: ${GRAFANA_TEMPO_PORT:6831}

rabbitmq:
  uri: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_IP}:${RABBITMQ_PORT}
  consumer-executor: rabbit
