environment: ${MICRONAUT_ENVIRONMENTS:local}
micronaut:
  application:
    name: ares
  server:
    port: 8086
    context-path: /payments
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  http:
    client:
      read-timeout: 30s
  executors:
    rabbit:
      type: FIXED
    consumer:
      type: FIXED

netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${DB_HOST:`rds-cluster.stage.cogoport.io`}:${DB_PORT:6432}/${DB_NAME:ares}?preparedStatementCacheQueries=0
      username: postgres
      password: A942B37CCFAF5A813B1432CAA209A43B9D144E47AD0DE1549C289C253E556CD5
      dialect: POSTGRES

services:
  service: https://api.stage.cogoport.io
  namespace: ${DNS_NAMESPACE:cogoport.stage}
  auth:
    alternateRoute: ${AUTH_ALTERNATE_ROUTE:true}
    authDisabled: ${AUTH_DISABLED:true}
    microserviceAuthToken: ${MS_AUTH_TOKEN:c3ad6b5c-a100-46e3-8728-8e2bf83f7de0}

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

opensearch:
  host: 'search.stage.cogoport.io'
  user: 'awsadmin'
  pass: Password@123

sentry:
  enabled: ${SENTRY_ENABLED:false}
  dsn: ${SENTRY_DSN:`https://10e833c953b04f429df6a6c8cae72c13@o435527.ingest.sentry.io/6475007`}

cogoport:
  api_url: https://api-mustangs4.dev.cogoport.io
  bearer_token: '7cff5415-6007-4bab-9f3e-e4a08c11e915'
  bearer_token_new: 0c320283-6f34-42d0-ac1d-e3390049fe65
  auth_scope_id: 0c320283-6f34-42d0-ac1d-e3390049fe65
  exchange_api:
    url: ${EXCHANGE_CLIENT_LAMBDA_URL:`https://api.cogoport.com/athena`}
    version: v1
    auth_token: ${EXCHANGE_API_AUTH_TOKEN:`a4f2243a-402e-4f24-825a-2747f66421c7`}

sage:
  soapUrl: http://13.126.196.22:8124/soap-generic/syracuse/collaboration/syracuse/CAdxWebServiceXmlCC
  user: admin
  password: admin@2
  queryClientUrl: https://gozaf35uzpkokesxfgw3g2ribi0hddzk.lambda-url.ap-south-1.on.aws
  queryClientPassword: KjjzzU2qneGMtzQQyFJ9QwEiPMFYZgut
  databaseName: 'COGO2'
  loginUrl: ${ SAGE_LOGIN_URL:`http://13.126.196.22/` }
  username: ${ SAGE_REST_API_USER:`rajveer.singh@cogoport.com` }
  userpassword: ${ SAGE_REST_API_PASSWORD:`Abcd@12345` }

ares:
  settlement:
    crossTradeParty: ${CROSS_TRADE_PARTY_SETTLEMENT:false}

aws:
  s3:
    bucket: business-finance-test

rabbitmq:
  uri: amqp://guest@localhost:5672
  consumer-executor: rabbit
