application:
  name: ares
server:
  port: 8086
  context-path: /payments
router:
  static-resources:
    swagger:
      paths: classpath:META-INF/swagger
      mapping: /swagger/**

netty:
  default:
    allocator:
      max-order: 3

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

r2dbc:
  datasources:
    default:
      datasources:
        default:
          url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?preparedStatementCacheQueries=0
          username: ${DB_USER}
          password: ${DB_PASSWORD}

kafka:
  health:
    enabled: false
  bootstrap:
    servers: ${KAFKA_SERVERS}
  security:
    protocol: SASL_SSL
  sasl:
    mechanism: AWS_MSK_IAM
    jaas:
      config: software.amazon.msk.auth.iam.IAMLoginModule required;
    client:
      callback:
        handler:
          class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

opensearch:
  host: ${OPENSEARCH_HOST}
  user: ${OPENSEARCH_USER}
  pass: ${OPENSEARCH_PASS}

cogoport:
  api_url: https://api-mustangs5.dev.cogoport.io
  bearer_token: '7cff5415-6007-4bab-9f3e-e4a08c11e915'
  bearer_token_new: 90fe8fd9-8760-4e1c-9f74-76c644f52c65
  auth_scope_id: e6efcc61-7e30-4d86-a901-e5d330113205

sage:
  soapUrl: http://13.126.196.22:8124/soap-generic/syracuse/collaboration/syracuse/CAdxWebServiceXmlCC
  user: admin
  password: admin@2
  queryClientUrl: https://gozaf35uzpkokesxfgw3g2ribi0hddzk.lambda-url.ap-south-1.on.aws
  queryClientPassword: KjjzzU2qneGMtzQQyFJ9QwEiPMFYZgut
  databaseName: 'COGO2'
  loginUrl: ${ SAGE_LOGIN_URL:`http://13.126.196.22/` }
  username: ${ SAGE_REST_API_USER:`rajveer.singh@cogoport.com` }
  userpassword: ${ SAGE_REST_API_PASSWORD:`Abcd@12345` }

tracing:
  exclusions:
    - /payments/prometheus
  jaeger:
    enabled: true
    sampler:
      probability: 1
    sender:
      agentHost: ${GRAFANA_TEMPO_DOMAIN:localhost}
      agentPort: ${GRAFANA_TEMPO_PORT:6831}
