micronaut:
  application:
    name: ares
  server:
    port: 8086
    context-path: /payment
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/ares
      username: cogoport
      password: cogoport123
      dialect: POSTGRES

kafka:
  bootstrap:
    servers: b-1.cogoport-staging.ulogbt.c2.kafka.ap-south-1.amazonaws.com:9098,b-2.cogoport-staging.ulogbt.c2.kafka.ap-south-1.amazonaws.com:9098
  security:
    protocol: SASL_SSL
  sasl:
    mechanism: AWS_MSK_IAM
    jaas:
      config: software.amazon.msk.auth.iam.IAMLoginModule required;
    client:
      callback:
        handler:
          class: software.amazon.msk.auth.iam.IAMClientCallbackHandler

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

opensearch:
  host: ${OPENSEARCH_HOST:search.books.dev.cogoport.io}
  user: ${OPENSEARCH_USER:books_search_dev}
  pass: ${OPENSEARCH_PASS:F20guhTISeCQ93nRaD@}
