environment: ${MICRONAUT_ENVIRONMENTS:dev}
micronaut:
  application:
    name: ares
  server:
    base-url: ${SITE_URL:`http://127.0.0.1:8086`}
    port: 8086
    context-path: /payments
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  http:
    client:
      read-timeout: 30s
  executors:
    rabbit:
      type: FIXED
    consumer:
      type: FIXED

opensearch:
  host: ${OPENSEARCH_HOST:localhost}
  user: ${OPENSEARCH_USER:admin}
  pass: ${OPENSEARCH_PASS:admin}
  scheme: http
  port: 9200

services:
  service:
    - id: bf-rails
      url: http://host.docker.internal:5000
      enabledLocally: true
    - id: hades
      url: https://api-mustangs2.dev.cogoport.io
      enabledLocally: true
  staging: https://api.stage.cogoport.io
  namespace: ${DNS_NAMESPACE:cogoport.stage}
  auth:
    alternateRoute: ${AUTH_ALTERNATE_ROUTE:true}
    authDisabled: ${AUTH_DISABLED:true}
    microserviceAuthToken: ${MS_AUTH_TOKEN:c3ad6b5c-a100-46e3-8728-8e2bf83f7de0}
