micronaut:
  application:
    name: ares
  server:
    port: 8086
    context-path: /payment
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/ares
      username: cogoport
      password: cogoport123
      dialect: POSTGRES

kafka:
  bootstrap:
    servers: localhost:29092

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

opensearch:
  host: ${OPENSEARCH_HOST:search.books.dev.cogoport.io}
  user: ${OPENSEARCH_USER:books_search_dev}
  pass: ${OPENSEARCH_PASS:F20guhTISeCQ93nRaD@}
