environment: ${MICRONAUT_ENVIRONMENTS:local}
micronaut:
  application:
    name: ares
  server:
    port: 8086
    context-path: /payments
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
    binders:
      r2dbc:
        enabled: false

netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${DB_HOST:`rds-cluster.stage.cogoport.io`}:${DB_PORT:6432}/${DB_NAME:ares}?preparedStatementCacheQueries=0
      username: postgres
      password: A942B37CCFAF5A813B1432CAA209A43B9D144E47AD0DE1549C289C253E556CD5
      dialect: POSTGRES

services:
  service: https://api.stage.cogoport.io
  namespace: ${DNS_NAMESPACE:cogoport.stage}

kafka:
  bootstrap:
    servers: localhost:29092

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

opensearch:
  host: 'search.stage.cogoport.io'
  user: 'awsadmin'
  pass: Password@123

sentry:
  enabled: ${SENTRY_ENABLED:false}
  dsn: ${SENTRY_DSN:`https://10e833c953b04f429df6a6c8cae72c13@o435527.ingest.sentry.io/6475007`}

cogoport:
  api_url: https://api-mustangs4.dev.cogoport.io
  bearer_token: '7cff5415-6007-4bab-9f3e-e4a08c11e915'
  bearer_token_new: 90fe8fd9-8760-4e1c-9f74-76c644f52c65
  auth_scope_id: fd4dae4d-9823-458a-9a25-710a8b1aae2e
  exchange_api:
    url: https://bfhdlimn73mhj66rq3ugx3h7ee0cazxm.lambda-url.ap-south-1.on.aws/
    version: v1
    auth_token: ${EXCHANGE_API_AUTH_TOKEN}

sage:
  soapUrl: http://13.232.139.45:8124/soap-generic/syracuse/collaboration/syracuse/CAdxWebServiceXmlCC
  user: admin
  password: admin@2
  queryClientUrl: https://gozaf35uzpkokesxfgw3g2ribi0hddzk.lambda-url.ap-south-1.on.aws
  queryClientPassword: KjjzzU2qneGMtzQQyFJ9QwEiPMFYZgut
  databaseName: 'COGO2'

ares:
  settlement:
    crossTradeParty: ${CROSS_TRADE_PARTY_SETTLEMENT:false}

aws:
  s3:
    bucket: business-finance-test

endpoints:
  prometheus:
    sensitive: false

otel:
  exporter:
    otlp:
      traces:
        endpoint: http://${GRAFANA_AGENT_DOMAIN:localhost}:${GRAFANA_AGENT_PORT:4317}
  service:
    name: ares
  traces:
    exporter: otlp
  exclusions:
    - /payments/prometheus