environment: ${MICRONAUT_ENVIRONMENTS:local}
micronaut:
  application:
    name: ares
  server:
    port: 8086
    context-path: /payments
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://ares.cxmkfxrc30yc.ap-south-1.rds.amazonaws.com:5432/ares?preparedStatementCacheQueries=0
      username: ares
      password: kce,A,yW9Bp0qNrQTysEjv^l5kQI-N
      dialect: POSTGRES

services:
  service: https://api.stage.cogoport.io
  namespace: ${DNS_NAMESPACE:cogoport.stage}

kafka:
  bootstrap:
    servers: localhost:29092

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

opensearch:
  host: 'search.stage.cogoport.io'
  user: 'awsadmin'
  pass: Password@123

sentry:
  enabled: ${SENTRY_ENABLED:false}
  dsn: ${SENTRY_DSN:`https://10e833c953b04f429df6a6c8cae72c13@o435527.ingest.sentry.io/6475007`}

cogoport:
  api_url: https://api-mustangs5.dev.cogoport.io
  bearer_token: '7cff5415-6007-4bab-9f3e-e4a08c11e915'
  exchange_api:
    url: https://bfhdlimn73mhj66rq3ugx3h7ee0cazxm.lambda-url.ap-south-1.on.aws/
    version: v1
    auth_token: a4f2243a-402e-4f24-825a-2747f66421c7

sage:
  soapUrl: http://13.232.139.45:8124/soap-generic/syracuse/collaboration/syracuse/CAdxWebServiceXmlCC
  user: admin
  password: admin@2
  queryClientUrl: https://gozaf35uzpkokesxfgw3g2ribi0hddzk.lambda-url.ap-south-1.on.aws
  queryClientPassword: KjjzzU2qneGMtzQQyFJ9QwEiPMFYZgut
  databaseName: 'COGO2'

ares:
  settlement:
    crossTradeParty: ${CROSS_TRADE_PARTY_SETTLEMENT:false}

aws:
  s3:
    bucket: business-finance-test
