ALTER TYPE service_type ADD VALUE 'TRAILER_FREIGHT';
ALTER TYPE service_type ADD VALUE 'STORE_ORDER';
ALTER TYPE service_type ADD VALUE 'ADDITIONAL_CHARGE';
ALTER TYPE service_type ADD VALUE 'FCL_CFS';
ALTER TYPE service_type ADD VALUE 'ORIGIN_SERVICES';
ALTER TYPE service_type ADD VALUE 'DESTINATION_SERVICES';