ALTER TYPE ACCOUNT_TYPE ADD VALUE 'WOFF';
ALTER TYPE ACCOUNT_TYPE ADD VALUE 'ROFF';
ALTER TYPE ACCOUNT_TYPE ADD VALUE 'EXCH';
ALTER TYPE ACCOUNT_TYPE ADD VALUE 'JVNOS';
ALTER TYPE ACCOUNT_TYPE ADD VALUE 'OUTST';