ALTER TYPE ACCOUNT_TYPE ADD VALUE 'ICJVBT';
ALTER TYPE ACCOUNT_TYPE ADD VALUE 'ICJVC';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE 'ICJVBT';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE 'ICJVC';
ALTER TYPE JV_CATEGORY ADD VALUE 'ICJVBT';
ALTER TYPE JV_CATEGORY ADD VALUE 'ICJVC';