CREATE TYPE SETTLEMENT_STATUS AS ENUM (
 'CREATED',
 'POSTED',
 'POSTING_FAILED');

 CREATE CAST (varchar AS SETTLEMENT_STATUS) WITH INOUT AS IMPLICIT;

ALTER TABLE payments ADD COLUMN sage_num_value varchar(25) DEFAULT NULL ;
ALTER TABLE settlements ADD COLUMN settlement_status SETTLEMENT_STATUS NOT NULL DEFAULT 'CREATED';