INSERT INTO journal_voucher_codes (number, description) VALUES
	('ACIXO', 'Axis O/D A/c-919030087386886'),
	('AXIO', 'AXIO-7762'),
	('AXIP', 'AXIP'),
	('AXISC', 'Axis Current'),
	('AXISP', 'AXISP-20029492479'),
	('BANK', 'BANK ENTRY'),
	('CCA', 'CC Avenue'),
	('CITI', 'Citi Bank Current'),
	('CITIS', 'Citi Singapore-21112003'),
	('CN', 'Reimbursement Invoice'),
	('CTDS', 'Customer TDS BANK'),
	('DBSC', 'DBS Current'),
	('DBSU', 'DBS EEFC -USD'),
	('DN', 'Reimbursement Invoice'),
	('GENAJ', 'Genral Journal'),
	('ICICC', 'ICICI Current'),
	('INDC', 'Indusind CA 201015563832'),
	('INDUA', 'Indusind bank-201015561001'),
	('INDUS', 'Indusind Current - 60301403308'),
	('INGE', 'ING Euro 095'),
	('INGG', 'ING GBP 686'),
	('INGU', 'ING USD account 769'),
	('INTER', 'Intercompany Journal Entry'),
	('KOTAC', 'Kotak Current'),
	('KOTOD', 'Kotak OD - 1412537955'),
	('KOTWC', 'Kotak WCDL Limit'),
	('MISC', 'Miscellaneous entry'),
	('MTC', 'Legal Match.'),
	('NEWPR', 'New Year'),
	('OPDIV', 'Miscellaneous entry'),
	('PIHI', 'Purchase Invoice'),
	('RAZO', 'Razorpay transactions'),
	('RBLC', 'RBL Current'),
	('RBLCP', 'RBLCP-2058'),
	('RBLD', 'RBL O/D A/c- 609000715480'),
	('RBLO', 'RBL O/D A/c- 609000632974'),
	('RBLPU', 'RBL USD A/C-409001685863'),
	('RBLU', 'RBL EEFC - USD'),
	('SIHI', 'Sales Invoice'),
	('TDS', 'TDS BANK'),
	('VTDS', 'Vendor TDS BANK');