DELETE FROM journal_voucher_categories where category ='SINV';
DELETE FROM journal_voucher_categories where category ='PINV';
DELETE FROM journal_voucher_categories where category ='PCN';
DELETE FROM journal_voucher_categories where category ='SCN';

Insert into journal_voucher_categories (category, description)
VALUES ('CTDS', 'Customer TDS'),
('CTDSP', 'Customer TDS 301'),
('VTDS', 'Vendor TDS');

INSERT INTO payment_sequence_numbers(sequence_type,next_sequence_number,created_at,updated_at)
VALUES('CTDS',100000000000,now(),now());

INSERT INTO payment_sequence_numbers(sequence_type,next_sequence_number,created_at,updated_at)
VALUES('CTDSP',100000000000,now(),now());

INSERT INTO payment_sequence_numbers(sequence_type,next_sequence_number,created_at,updated_at)
VALUES('VTDS',100000000000,now(),now());

ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CTDSP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'VTDS';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CTDS';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CTDSP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CTDS';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'VTDS';
ALTER TYPE PAYMENT_CODE ADD VALUE IF NOT EXISTS 'CTDSP';
ALTER TYPE PAYMENT_CODE ADD VALUE IF NOT EXISTS 'CTDS';
ALTER TYPE PAYMENT_CODE ADD VALUE IF NOT EXISTS 'VTDS';


ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CSINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'SPINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CSMEM';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSMEM';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'SPMEM';

ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CSINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'SPINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CSMEM';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSMEM';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'SPMEM';

UPDATE journal_voucher_categories SET category = 'PAYJV' WHERE category = 'PAY';
UPDATE journal_voucher_categories SET category = 'RECJV' WHERE category = 'REC';