INSERT INTO journal_voucher_categories
(category, description)
VALUES
('BANK', 'Bank Entry'),
('CLOS1', 'Closing Year End / Legal'),
('CLOS1', 'Clôture'),
('CLOSE', 'Fecho'),
('CONTR', 'CONTRA'),
('CRRCV', 'N/Créd. a receber'),
('CSDIR', 'Прямые продажи (сф)'),
('CSINV', 'Customer Invoice'),
('CSMEM', 'Customer Memo'),
('CSTRV', 'Révision coût standard'),
('CURVR', 'Desvio de conversão'),
('DBTRC', 'Faltas pagamento'),
('EXPNS', 'Notas de Despesa'),
('FAAR2', 'OD Immo ana'),
('FAAR2', 'OD Imob anal.'),
('FAIR3', 'OD Immo IAS'),
('FAIR3', 'OD Imob IAS'),
('FAIS3', 'OD Imob simul. IAS'),
('FAIS3', 'OD Inmo simulación IAS'),
('FAR12', 'OD Imno social & ana'),
('FAR12', 'OD Imob. social & anal.'),
('FAS12', 'OD Imno simul. social & ana'),
('FAS12', 'OD Inmo simul. legal y ana'),
('FIXDP', 'Fixed Asset Depreciation'),
('GEN', 'Opérations diverses'),
('GENAJ', 'Pagamento'),
('GENSM', 'Simulação Geral'),
('INTER', 'Miscellaneous entry'),
('MFIIS', 'Interface Produção'),
('MFIOP', 'Interface Prod Oper.'),
('MFIRC', 'Interface Produção - Recep.'),
('MISC', 'Misc JV'),
('MISC', 'Misc Journal Entry'),
('MSCOP', 'Opérations Diverses'),
('MTC', 'Legal Match.'),
('MTCCV', 'Matching-Currency Variance'),
('NEWPR', 'A nouveaux USA'),
('NEWPR', 'New Period'),
('OPDIV', 'Miscellaneous entry'),
('PAY', 'AP Payment'),
('PAYMT', 'Pagos'),
('PAYRL', 'OD de nómina'),
('PREPY', 'Acomptes'),
('REC', 'AR RECEIPT'),
('RECJL', 'Pagos'),
('RECP', 'Payment Receipt'),
('RECPT', 'Payment Receipt'),
('RPI', 'Reimbursement Invoice'),
('SAINV', 'Faturas clientes'),
('SPDIR', 'Achats - Factures directes'),
('SPINV', 'Supplier Invoice'),
('SPMEM', 'Supplier Credit Memo'),
('SPMEM', 'Supplier Memo'),
('STMNT', 'Relevés de factures'),
('STOCK', 'Movimentos Stock'),
('UNRIN', 'Facturas a receber'),
('WIPCO', 'Work In Progress / Unf. Leist.'),
('WIPCS', 'Em Curso'),
('ZDN', 'Reimbursement Invoice'),
('ZSDN', 'Customer Debit Note'),
('ZSINV', 'Customer Invoice'),
('ZSMEM', 'Customer Memo'),
('ZSMEP', 'Customer Memo'),
('ZSMFR', 'Minus Freight');

ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'GENSM';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSMEP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'PAYMT';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'SPMEM';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FAIS3';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'SPDIR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'GEN';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'NEWPR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'PAYRL';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CSMEM';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'BANK';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CONTR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'STOCK';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MTC';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'WIPCO';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'SPINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'RECP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MSCOP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'INTER';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FAS12';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'RECJL';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'OPDIV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CLOS1';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZDN';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'UNRIN';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MFIRC';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'PREPY';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FIXDP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FAIR3';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'DBTRC';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'WIPCS';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MFIOP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CSTRV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'RECPT';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CRRCV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CLOSE';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSMFR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'SAINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSMEM';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'RPI';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'EXPNS';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MFIIS';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FAR12';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CURVR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'GENAJ';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSDN';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CSDIR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MTCCV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MISC';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CSINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'STMNT';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FAAR2';


ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'GENSM';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSMEP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'PAYMT';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'SPMEM';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FAIS3';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'SPDIR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'GEN';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'NEWPR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'PAYRL';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CSMEM';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'BANK';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CONTR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'STOCK';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MTC';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'WIPCO';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'SPINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'RECP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MSCOP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'INTER';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FAS12';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'RECJL';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'OPDIV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CLOS1';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZDN';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'UNRIN';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MFIRC';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'PREPY';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FIXDP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FAIR3';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'DBTRC';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'WIPCS';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MFIOP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CSTRV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'RECPT';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CRRCV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CLOSE';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSMFR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'SAINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSMEM';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'RPI';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'EXPNS';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MFIIS';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FAR12';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CURVR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'GENAJ';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSDN';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CSDIR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MTCCV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MISC';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CSINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'STMNT';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FAAR2';