ALTER TABLE parent_journal_vouchers
ADD COLUMN entity_code int2 DEFAULT NULL,
ADD COLUMN transaction_date DATE DEFAULT NULL,
ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL,
ADD COLUMN is_utilized BOOLEAN DEFAULT FALSE;

ALTER TABLE parent_journal_vouchers DROP COLUMN amount;
ALTER TABLE parent_journal_vouchers DROP COLUMN acc_mode;

ALTER TABLE journal_vouchers
ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;

ALTER TABLE journal_voucher_categories DROP COLUMN default_journal_code;
ALTER TABLE journal_voucher_categories DROP COLUMN entity_code;
ALTER TABLE journal_voucher_categories DROP COLUMN country_code;
ALTER TABLE journal_voucher_categories DROP COLUMN valid_start;
ALTER TABLE journal_voucher_categories DROP COLUMN valid_end;
ALTER TABLE journal_voucher_categories DROP COLUMN created_by;
ALTER TABLE journal_voucher_categories DROP COLUMN updated_by;

ALTER TABLE journal_voucher_codes DROP COLUMN entity_code;
ALTER TABLE journal_voucher_codes DROP COLUMN country_code;
ALTER TABLE journal_voucher_codes DROP COLUMN jv_category_id;
ALTER TABLE journal_voucher_codes DROP COLUMN created_by;
ALTER TABLE journal_voucher_codes DROP COLUMN updated_by;

CREATE TABLE public.account_classes (
    id BIGSERIAL CONSTRAINT account_class_PK PRIMARY KEY,
    led_account VARCHAR,
    account_category VARCHAR,
    class_code INT,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP not null default now(),
    updated_at TIMESTAMP not null default now()
);

CREATE TABLE public.gl_code_masters (
    id BIGSERIAL CONSTRAINT gl_code_master_PK PRIMARY KEY,
    account_code INT,
    description VARCHAR,
    led_account VARCHAR,
    account_type VARCHAR,
    class_code INT,
    account_class_id BIGINT NOT NULL REFERENCES account_classes (id) ON DELETE CASCADE,
    created_by UUID,
    updated_by UUID,
    created_at TIMESTAMP not null default now(),
    updated_at TIMESTAMP not null default now()
);

ALTER TYPE account_mode ADD VALUE 'RE';
ALTER TYPE account_mode ADD VALUE 'PREF';
ALTER TYPE account_mode ADD VALUE 'EMP';
ALTER TYPE account_mode ADD VALUE 'RI';
ALTER TYPE account_mode ADD VALUE 'PC';

INSERT INTO account_classes (led_account, account_category, class_code, created_by, updated_by) VALUES
	('IND', 'Equity', '01', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('IND', 'Non Current Assets', '02', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('IND', 'Current Assets', '03', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('IND', 'Liability', '04', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('IND', 'Current Liability', '05', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('IND', 'Provision', '06', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('IND', 'Revenue', '07', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('IND', 'Direct Expense', '08', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('IND', 'Indirect Expense', '09', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('IND', 'Indirect Income', '10', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('NL', 'Equity', '01', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('NL', 'Non Current Assets', '02', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('NL', 'Current Assets', '03', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('NL', 'Liability', '04', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('NL', 'Current Liability', '05', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('NL', 'Provision', '06', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('NL', 'Revenue', '07', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('NL', 'Direct Expense', '08', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('NL', 'Indirect Expense', '09', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('NL', 'Indirect Income', '10', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('SGP', 'Equity', '01', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('SGP', 'Non Current Assets', '02', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('SGP', 'Current Assets', '03', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('SGP', 'Liability', '04', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('SGP', 'Current Liability', '05', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('SGP', 'Provision', '06', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('SGP', 'Revenue', '07', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('SGP', 'Direct Expense', '08', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('SGP', 'Indirect Expense', '09', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441'),
	('SGP', 'Indirect Income', '10', 'c4f72139-e4b9-4cea-b590-32cea179f441', 'c4f72139-e4b9-4cea-b590-32cea179f441');

INSERT INTO journal_voucher_codes (number, description) VALUES
	('ACIXO', 'Axis O/D A/c-919030087386886'),
	('AXIO', 'AXIO-7762'),
	('AXIP', 'AXIP'),
	('AXISC', 'Axis Current'),
	('AXISP', 'AXISP-20029492479'),
	('BANK', 'BANK ENTRY'),
	('CCA', 'CC Avenue'),
	('CITI', 'Citi Bank Current'),
	('CITIS', 'Citi Singapore-21112003'),
	('CN', 'Reimbursement Invoice'),
	('CTDS', 'Customer TDS BANK'),
	('DBSC', 'DBS Current'),
	('DBSU', 'DBS EEFC -USD'),
	('DN', 'Reimbursement Invoice'),
	('GENAJ', 'Genral Journal'),
	('ICICC', 'ICICI Current'),
	('INDC', 'Indusind CA 201015563832'),
	('INDUA', 'Indusind bank-201015561001'),
	('INDUS', 'Indusind Current - 60301403308'),
	('INGE', 'ING Euro 095'),
	('INGG', 'ING GBP 686'),
	('INGU', 'ING USD account 769'),
	('INTER', 'Intercompany Journal Entry'),
	('KOTAC', 'Kotak Current'),
	('KOTOD', 'Kotak OD - 1412537955'),
	('KOTWC', 'Kotak WCDL Limit'),
	('MISC', 'Miscellaneous entry'),
	('MTC', 'Legal Match.'),
	('NEWPR', 'New Year'),
	('OPDIV', 'Miscellaneous entry'),
	('PIHI', 'Purchase Invoice'),
	('RAZO', 'Razorpay transactions'),
	('RBLC', 'RBL Current'),
	('RBLCP', 'RBLCP-2058'),
	('RBLD', 'RBL O/D A/c- 609000715480'),
	('RBLO', 'RBL O/D A/c- 609000632974'),
	('RBLPU', 'RBL USD A/C-409001685863'),
	('RBLU', 'RBL EEFC - USD'),
	('SIHI', 'Sales Invoice'),
	('TDS', 'TDS BANK'),
	('VTDS', 'Vendor TDS BANK');

INSERT INTO journal_voucher_categories
(category, description)
VALUES
('BANK', 'Bank Entry'),
('CLOS1', 'Closing Year End / Legal'),
('CLOS1', 'Clôture'),
('CLOSE', 'Fecho'),
('CONTR', 'CONTRA'),
('CRRCV', 'N/Créd. a receber'),
('CSDIR', 'Прямые продажи (сф)'),
('CSINV', 'Customer Invoice'),
('CSMEM', 'Customer Memo'),
('CSTRV', 'Révision coût standard'),
('CURVR', 'Desvio de conversão'),
('DBTRC', 'Faltas pagamento'),
('EXPNS', 'Notas de Despesa'),
('FAAR2', 'OD Immo ana'),
('FAAR2', 'OD Imob anal.'),
('FAIR3', 'OD Immo IAS'),
('FAIR3', 'OD Imob IAS'),
('FAIS3', 'OD Imob simul. IAS'),
('FAIS3', 'OD Inmo simulación IAS'),
('FAR12', 'OD Imno social & ana'),
('FAR12', 'OD Imob. social & anal.'),
('FAS12', 'OD Imno simul. social & ana'),
('FAS12', 'OD Inmo simul. legal y ana'),
('FIXDP', 'Fixed Asset Depreciation'),
('GEN', 'Opérations diverses'),
('GENAJ', 'Pagamento'),
('GENSM', 'Simulação Geral'),
('INTER', 'Miscellaneous entry'),
('MFIIS', 'Interface Produção'),
('MFIOP', 'Interface Prod Oper.'),
('MFIRC', 'Interface Produção - Recep.'),
('MISC', 'Misc JV'),
('MISC', 'Misc Journal Entry'),
('MSCOP', 'Opérations Diverses'),
('MTC', 'Legal Match.'),
('MTCCV', 'Matching-Currency Variance'),
('NEWPR', 'A nouveaux USA'),
('NEWPR', 'New Period'),
('OPDIV', 'Miscellaneous entry'),
('PAY', 'AP Payment'),
('PAYMT', 'Pagos'),
('PAYRL', 'OD de nómina'),
('PREPY', 'Acomptes'),
('REC', 'AR RECEIPT'),
('RECJL', 'Pagos'),
('RECP', 'Payment Receipt'),
('RECPT', 'Payment Receipt'),
('RPI', 'Reimbursement Invoice'),
('SAINV', 'Faturas clientes'),
('SPDIR', 'Achats - Factures directes'),
('SPINV', 'Supplier Invoice'),
('SPMEM', 'Supplier Credit Memo'),
('SPMEM', 'Supplier Memo'),
('STMNT', 'Relevés de factures'),
('STOCK', 'Movimentos Stock'),
('UNRIN', 'Facturas a receber'),
('WIPCO', 'Work In Progress / Unf. Leist.'),
('WIPCS', 'Em Curso'),
('ZDN', 'Reimbursement Invoice'),
('ZSDN', 'Customer Debit Note'),
('ZSINV', 'Customer Invoice'),
('ZSMEM', 'Customer Memo'),
('ZSMEP', 'Customer Memo'),
('ZSMFR', 'Minus Freight');

ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'GENSM';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSMEP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'PAYMT';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'SPMEM';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FAIS3';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'SPDIR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'GEN';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'NEWPR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'PAYRL';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CSMEM';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'BANK';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CONTR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'STOCK';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MTC';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'WIPCO';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'SPINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'RECP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MSCOP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'INTER';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FAS12';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'RECJL';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'OPDIV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CLOS1';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZDN';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'UNRIN';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MFIRC';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'PREPY';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FIXDP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FAIR3';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'DBTRC';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'WIPCS';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MFIOP';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CSTRV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'RECPT';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CRRCV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CLOSE';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSMFR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'SAINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSMEM';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'RPI';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'EXPNS';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MFIIS';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FAR12';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CURVR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'GENAJ';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'ZSDN';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CSDIR';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MTCCV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'MISC';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'CSINV';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'STMNT';
ALTER TYPE ACCOUNT_TYPE ADD VALUE IF NOT EXISTS 'FAAR2';


ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'GENSM';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSMEP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'PAYMT';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'SPMEM';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FAIS3';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'SPDIR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'GEN';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'NEWPR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'PAYRL';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CSMEM';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'BANK';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CONTR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'STOCK';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MTC';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'WIPCO';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'SPINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'RECP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MSCOP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'INTER';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FAS12';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'RECJL';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'OPDIV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CLOS1';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZDN';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'UNRIN';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MFIRC';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'PREPY';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FIXDP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FAIR3';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'DBTRC';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'WIPCS';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MFIOP';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CSTRV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'RECPT';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CRRCV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CLOSE';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSMFR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'SAINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSMEM';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'RPI';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'EXPNS';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MFIIS';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FAR12';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CURVR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'GENAJ';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'ZSDN';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CSDIR';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MTCCV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'MISC';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'CSINV';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'STMNT';
ALTER TYPE SETTLEMENT_TYPE ADD VALUE IF NOT EXISTS 'FAAR2';

 CREATE TYPE SETTLEMENT_STATUS AS ENUM (
  'CREATED',
  'POSTED',
  'POSTING_FAILED',
  'DELETED');

  CREATE CAST (varchar AS SETTLEMENT_STATUS) WITH INOUT AS IMPLICIT;

 ALTER TABLE settlements ADD COLUMN settlement_status SETTLEMENT_STATUS NOT NULL DEFAULT 'CREATED';