CREATE TABLE ledger_summary (
    id SERIAL PRIMARY KEY,
    organization_id UUID,
    entity_code INT,
    led_currency VARCHAR(50),
    organization_name VARCHAR(255),
    acc_mode public."account_mode" NOT NULL,
    invoice_not_due_amount NUMERIC(18, 4),
    invoice_today_amount NUMERIC(18, 4),
    invoice_thirty_amount NUMERIC(18, 4),
    invoice_sixty_amount NUMERIC(18, 4),
    invoice_ninety_amount NUMERIC(18, 4),
    invoice_one_eighty_amount NUMERIC(18, 4),
    invoice_three_sixty_five_amount NUMERIC(18, 4),
    invoice_three_sixty_five_plus_amount NUMERIC(18, 4),
    invoice_not_due_count BIGINT,
    invoice_today_count BIGINT,
    invoice_thirty_count BIGINT,
    invoice_sixty_count BIGINT,
    invoice_ninety_count BIGINT,
    invoice_one_eighty_count BIGINT,
    invoice_three_sixty_five_count BIGINT,
    invoice_three_sixty_five_plus_count BIGINT,
    credit_note_count BIGINT,
    on_account_not_due_amount NUMERIC(18, 4),
    on_account_today_amount NUMERIC(18, 4),
    on_account_thirty_amount NUMERIC(18, 4),
    on_account_sixty_amount NUMERIC(18, 4),
    on_account_ninety_amount NUMERIC(18, 4),
    on_account_one_eighty_amount NUMERIC(18, 4),
    on_account_three_sixty_five_amount NUMERIC(18, 4),
    on_account_three_sixty_five_plus_amount NUMERIC(18, 4),
    on_account_not_due_count BIGINT,
    on_account_today_count BIGINT,
    on_account_thirty_count BIGINT,
    on_account_sixty_count BIGINT,
    on_account_ninety_count BIGINT,
    on_account_one_eighty_count BIGINT,
    on_account_three_sixty_five_count BIGINT,
    on_account_three_sixty_five_plus_count BIGINT,
    not_due_outstanding NUMERIC(18, 4),
    today_outstanding NUMERIC(18, 4),
    thirty_outstanding NUMERIC(18, 4),
    sixty_outstanding NUMERIC(18, 4),
    ninety_outstanding NUMERIC(18, 4),
    one_eighty_outstanding NUMERIC(18, 4),
    three_sixty_five_outstanding NUMERIC(18, 4),
    three_sixty_five_plus_outstanding NUMERIC(18, 4),
    total_open_invoice_amount NUMERIC(18, 4),
    total_credit_note_amount NUMERIC(18, 4),
    total_on_account_amount NUMERIC(18, 4),
    total_outstanding NUMERIC(18, 4),
    created_at DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT unique_created_at_organization_id UNIQUE (created_at, organization_id)
)