ALTER TYPE stakeholder_type ADD VALUE 'TRADE_FINANCE_AGENT';
ALTER TYPE stakeholder_type ADD VALUE 'ENTITY_MANAGER';
ALTER TYPE stakeholder_type ADD VALUE 'SUPPLY_AGENT';
ALTER TYPE stakeholder_type ADD VALUE 'SALES_AGENT';
ALTER TYPE stakeholder_type ADD VALUE 'BOOKING_AGENT';
ALTER TYPE stakeholder_type ADD VALUE 'PORTFOLIO_MANAGER';
ALTER TYPE stakeholder_type ADD VALUE 'CKAM';
