version: "3.9" 
services:

  db: 
    image: postgres:14.2-alpine3.15
    ports:
      - "5432:5432"
    restart: on-failure
    env_file:
      - '.env.test'

  opensearch:
    image: opensearchproject/opensearch:2.2.1
    container_name: opensearch-node1
    env_file:
      - '.env.test'
    ports:
      - "9200:9200"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.2.1
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"

  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

