version: "3.9" 
services:
  db: 
    image: postgres:14.2-alpine3.15
    ports:
      - "5432:5432"
    volumes:
      - "ares_data:/var/lib/postgresql/data"
    restart: on-failure
    env_file:
      - '.env.local'

  kafka:
    image: bitnami/kafka:2.8.1
    ports:
    - "29092:29092"
    env_file:
      - '.env.local'
    depends_on:
      - zookeeper
  
  zookeeper:
    image: zookeeper:3.8.0
    hostname: zookeeper
    ports:
    - "2181:2181"
    env_file:
      - '.env.local'

  kafdrop:
    image: obsidiandynamics/kafdrop:3.29.0
    restart: on-failure
    ports:
      - "9000:9000"
    env_file:
      - '.env.local'
    depends_on:
      - "kafka"

  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  ares_data:


