version: "3.9" 
services:
  ares-db:
    image: postgres:14.2-alpine3.15
    ports:
      - "5433:5432"
    volumes:
      - "ares_data:/var/lib/postgresql/data"
    restart: on-failure
    env_file:
      - '.env'

#  kafka:
#    image: bitnami/kafka:2.8.1
#    ports:
#    - "29092:9092"
#    env_file:
#      - '.env'
#    depends_on:
#      - zookeeper
#
#  zookeeper:
#    image: zookeeper:3.8.0
#    hostname: zookeeper
#    ports:
#    - "2181:2181"
#    env_file:
#      - '.env'
#
#  kafdrop:
#    image: obsidiandynamics/kafdrop:3.29.0
#    restart: on-failure
#    ports:
#      - "9000:9000"
#    env_file:
#      - '.env'
#    depends_on:
#      - "kafka"

volumes:
  ares_data:


