version: "3.9" 
services:
  db: 
    image: postgres:14.2-alpine3.15
    ports:
      - "5432:5432"
    volumes:
      - "ares_data:/var/lib/postgresql/data"
    restart: on-failure
    env_file:
      - '.env.local'

  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  ares_data:


