name: PR-Check
on:
  pull_request:
jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3

      # https://github.com/marketplace/actions/run-ktlint-with-reviewdog
      - uses: ScaCap/action-ktlint@v1.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ktlint_version: '0.45.2'
          reporter: github-pr-check
          fail_on_error: true
#  detekt:
#    runs-on: ubuntu-latest
#
#    steps:
#      # https://github.com/marketplace/actions/checkout
#      - uses: actions/checkout@v3
#
#      # https://github.com/marketplace/actions/run-detekt-with-reviewdog
#      - name: Run detekt with reviewdog
#        uses: alaegin/Detekt-Action@v1.22.0-RC3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          detekt_config: config/detekt/detekt.yml
#          reporter: github-pr-review
#          fail_on_error: false