name: Unit Tests
on: 
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  checks: write
  contents: read
  issues: read

env:
  GITHUB_USERNAME: ${{ secrets.RW_PACKAGE_TOKEN_COGOPORT_DEV }}
  GITHUB_TOKEN: cogoport-dev

jobs:
  Tests:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == ':runTests'}}
    runs-on: cogo-action-runner
    steps:
      - uses: actions/checkout@master
      - name: Cache Gradle
        uses: actions/setup-java@master
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Checkout Pull Request
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Environment Variables
        run: |
          echo "LATEST_COMMIT_HASH=$(git rev-parse --verify HEAD)" >> $GITHUB_ENV
          
      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml up --abort-on-container-exit
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with: 
          junit_files: |
            ./api/build/test-results/**/*.xml
            ./model/build/test-results/**/*.xml
            ./client/build/test-results/**/*.xml
            
          check_run_annotations_branch: "*"
          commit: ${{ env.LATEST_COMMIT_HASH }}
          comment_mode: create new
